# Generated by Django 4.2.4 on 2023-09-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('new_date', models.DateField(auto_now_add=True)),
                ('pass_due_date', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('is_editing', models.BooleanField(default=False)),
            ],
        ),
    ]
