# Generated by Django 4.2.4 on 2023-09-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='new_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='is_editing',
            new_name='editting',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='pass_due_date',
            new_name='expired',
        ),
    ]
